### PR TITLE
Add nvmrc file with instructions

### PR DESCRIPTION
**Pull request by jamesmontalvo3**
@cameronwp I think you determined that the contents of this PR were not the direction you recommended for now. This branch was just sitting out there untouched, so I'm creating the PR so we can document the decision here. If this should be merged, we can merge it. If not, we can close it and have some history regarding the decision.

### CODE REVIEW

**Comment by cameronwp** [comment]
For reference: https://github.com/xOPERATIONS/maestro/issues/82

I stand by my comments there. I'd like to close this PR for now because of the potential confusion to non-technical users who want to install `maestro`.

However, if we decide to distribute pre-built `maestro` binaries in the future, I would happily merge this PR.

**Comment by cameronwp** [comment]
This could be useful for packaging: https://github.com/zeit/pkg

Any thoughts? If you'd like, @jamesmontalvo3, I could look into something like ^^^ as a means of distribution with an updated installation process. I'm thinking we'd upload the "binaries" to the releases tab in github and instruct folks to download it there. We can write out shell scripts to install and put the binaries on the user's `$PATH`.

**Comment by jamesmontalvo3** [comment]
Let's talk this when we meet later.

**Comment by jamesmontalvo3** [comment]
Closing this for now. Will readdress later when node versions become an issue or perhaps will use something like https://github.com/zeit/pkg when more users (who don't want to install Node) are using Maestro.

**Pull request closed without merging**
